### ISSUE TITLE
EmojiLibrary not working on unc0ver 5.2.0

### ISSUE THREAD

**Issue by parsifall** [PoomSmart/EmojiLibrary#11]
Device info: iPhone 7, iOS 12.0.1, unc0ver 5.2.0 jailbreak.
Problem: since I’ve upgraded from unc0ver 4.3.0 to 5.2.0 I don’t see any iOS 13.2 emoji, I’ve installed both EmojiLibrary and EmojiPort latest beta updates (says iOS 13 supported). Any clue?

**Comment by PoomSmart** [comment]
Fixed in 1.1.4~b2

**Comment by parsifall** [comment]
Problem persists: I reinstalled EmojiFontManager, EmojiLibrary, EmojiPort and Emoji iOS 13.2, still emojis doesn’t show in keyboard and see "?" character in texts

**Comment by parsifall** [comment]
C

**Comment by PoomSmart** [comment]
Well then, I presume this is sandbox issue that certain apps can’t load the emoji font that is located outside of their container.

**Comment by parsifall** [comment]
If I delete the CoreFoundationVersion field in EmojiPortPE.plist emojis shows again

**Comment by PoomSmart** [comment]
Alright, I guess I know what’s going on.
